[package]
name = "user_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
buddy-allocator = { path = "../buddy-allocator" }
bitflags = "1.2.1"

[profile.release]
debug = true